name: 'setup-psychopy'
description: 'Setup psychopy on CIs'
author: Mathieu Scheltienne
branding:
  icon: 'circle'
  color: 'black'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: ${{ github.workspace }}/auto.sh
