name: 'setup-psychopy'
description: 'Setup psychopy on CIs'
author: Mathieu Scheltienne
branding:
  icon: 'circle'
  color: 'black'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          ${{ github.workspace }}\auto.sh
        else
          ${{ github.workspace }}/auto.sh
        fi
